import Head from 'next/head'
import Grid from '../components/grid/grid';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Grid</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='container'>
        <Grid />
      </div>
    </div>
  )
}
